import asyncio
from app.database.session import AsyncSessionLocal
from app.models.report import ReportTemplate
from app.models.notification import NotificationTemplate, NotificationChannel
import uuid

welcome_email_html = """
<!DOCTYPE html>
<html>
<body>
    <h2>Welcome to Legal AI System, {{name}}!</h2>
    <p>Your account ({{email}}) has been successfully registered.</p>
    <p>Please log in to complete your profile.</p>
</body>
</html>
"""

case_created_html = """
<!DOCTYPE html>
<html>
<body>
    <h2>Case {{case_number}} Created</h2>
    <p>Your case titled '{{title}}' has been successfully created in the system.</p>
    <p>An advocate will be assigned shortly.</p>
</body>
</html>
"""

document_uploaded_html = """
<!DOCTYPE html>
<html>
<body>
    <h2>New Document Uploaded to Case {{case_number}}</h2>
    <p>{{uploader_name}} has uploaded a new document: '{{document_name}}'.</p>
    <p>Please review it in your case dashboard.</p>
</body>
</html>
"""

password_reset_html = """
<!DOCTYPE html>
<html>
<body>
    <h2>Password Reset Request</h2>
    <p>You requested a password reset for your Legal AI System account.</p>
    <p>Please click the following link to reset your password:</p>
    <p><a href="{{reset_link}}">Reset Password</a></p>
    <p>This link will expire in 1 hour.</p>
</body>
</html>
"""

case_assigned_html = """
<!DOCTYPE html>
<html>
<body>
    <h2>New Case Assigned: {{case_number}}</h2>
    <p>You have been assigned to Case {{case_number}} as an {{role}}.</p>
    <p>Please log in to your dashboard to review the case details.</p>
</body>
</html>
"""

payment_success_html = """
<!DOCTYPE html>
<html>
<body>
    <h2>Payment Successful</h2>
    <p>We have successfully received your payment of ${{payment_amount}}.</p>
    <p>Reference: {{reference}}</p>
    <p>Thank you for using Legal AI System.</p>
</body>
</html>
"""

report_ready_html = """
<!DOCTYPE html>
<html>
<body>
    <h2>Legal Report Ready</h2>
    <p>Your legal report '{{report_name}}' for Case {{case_number}} is now ready to view.</p>
    <p>Please log in to your dashboard to access the report.</p>
</body>
</html>
"""

standard_template_html = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Standard Legal Report</title>
    <style>
        @page {
            size: A4;
            margin: 2cm;
            @bottom-right {
                content: "Page " counter(page) " of " counter(pages);
                font-family: Arial, sans-serif;
                font-size: 10pt;
                color: #666;
            }
        }
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #1a365d;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #1a365d;
            margin: 0;
            text-transform: uppercase;
        }
        .section {
            margin-bottom: 25px;
        }
        .section h2 {
            color: #2c5282;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 5px;
        }
        .meta-data {
            background-color: #f7fafc;
            padding: 15px;
            border-left: 4px solid #3182ce;
            margin-bottom: 30px;
        }
        .meta-data table {
            width: 100%;
        }
        .meta-data td {
            padding: 5px 0;
        }
        .label {
            font-weight: bold;
            width: 150px;
        }
        .signature {
            margin-top: 60px;
            text-align: right;
        }
        .signature-line {
            display: inline-block;
            border-top: 1px solid #000;
            width: 250px;
            text-align: center;
            padding-top: 10px;
        }
        .watermark {
            position: fixed;
            top: 40%;
            left: 20%;
            font-size: 100pt;
            color: rgba(0, 0, 0, 0.05);
            transform: rotate(-45deg);
            z-index: -1;
        }
    </style>
</head>
<body>
    <div class="watermark">CONFIDENTIAL</div>
    
    <div class="header">
        <h1>Legal Opinion Report</h1>
        <p>Generated by Legal AI System</p>
    </div>

    <div class="meta-data">
        <table>
            <tr><td class="label">Case Title:</td><td>{{ case.title }}</td></tr>
            <tr><td class="label">Client Name:</td><td>{{ case.client.full_name if case.client else 'Unknown' }}</td></tr>
            <tr><td class="label">Case Type:</td><td>{{ case.category }}</td></tr>
            <tr><td class="label">Date Generated:</td><td>{{ generated_at }}</td></tr>
        </table>
    </div>

    <div class="section">
        <h2>1. Executive Summary</h2>
        <div>{{ opinion.summary | default('No executive summary available.', true) }}</div>
    </div>

    <div class="section">
        <h2>2. Facts of the Case</h2>
        <div>{{ opinion.facts | default('No facts available.', true) }}</div>
    </div>

    <div class="section">
        <h2>3. Legal Analysis</h2>
        <div>{{ opinion.legal_analysis | default('No legal analysis available.', true) }}</div>
    </div>

    <div class="section">
        <h2>4. Risk Assessment</h2>
        <p><strong>Risk Level:</strong> {{ opinion.risk_level.value if opinion.risk_level else 'Unknown' }}</p>
        <p><strong>Winning Probability:</strong> {{ opinion.winning_probability }}%</p>
    </div>

    <div class="section">
        <h2>5. Recommendations</h2>
        <div>{{ opinion.recommendations | default('No recommendations available.', true) }}</div>
    </div>

    <div class="signature">
        <div class="signature-line">
            Authorized Signature
        </div>
    </div>
</body>
</html>
"""

async def seed_templates():
    async with AsyncSessionLocal() as db:
        # Check if exists
        from sqlalchemy import select
        result = await db.execute(select(ReportTemplate).where(ReportTemplate.name == "Standard Legal Report"))
        existing = result.scalars().first()
        
        if not existing:
            template = ReportTemplate(
                id=uuid.uuid4(),
                name="Standard Legal Report",
                template_type="Standard",
                html_content=standard_template_html
            )
            db.add(template)
            await db.commit()
            print("Template seeded successfully!")
        else:
            existing.html_content = standard_template_html
            await db.commit()
            print("Template updated successfully!")
            
        # Seed Notification Templates
        notification_templates = [
            ("Welcome Email", "Welcome to Legal AI System!", welcome_email_html),
            ("Case Created", "Your Case {{case_number}} has been created", case_created_html),
            ("Document Uploaded", "New Document for Case {{case_number}}", document_uploaded_html),
            ("Password Reset", "Password Reset Request", password_reset_html),
            ("Case Assigned", "New Case Assigned: {{case_number}}", case_assigned_html),
            ("Payment Success", "Payment Successful", payment_success_html),
            ("Report Ready", "Your Legal Report is Ready", report_ready_html)
        ]
        
        from sqlalchemy import select
        for name, subject, html in notification_templates:
            result = await db.execute(select(NotificationTemplate).where(NotificationTemplate.name == name))
            existing_notif = result.scalars().first()
            if not existing_notif:
                t = NotificationTemplate(name=name, subject_template=subject, body_template=html, channel=NotificationChannel.EMAIL)
                db.add(t)
            else:
                existing_notif.subject_template = subject
                existing_notif.body_template = html
        
        await db.commit()
        print("Notification templates seeded successfully!")

if __name__ == "__main__":
    asyncio.run(seed_templates())
