"""Add notice filing and hearing dates to case

Revision ID: 0f0556a444b3
Revises: 983f09845dc1
Create Date: 2026-08-13 15:39:03.614811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0556a444b3'
down_revision: Union[str, None] = '983f09845dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('notice_date', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('filing_date', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('next_hearing_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'next_hearing_date')
    op.drop_column('cases', 'filing_date')
    op.drop_column('cases', 'notice_date')
    # ### end Alembic commands ###
