"""Update AISummary for new legal brief schema

Revision ID: 279b177d4e6e
Revises: f260b6863262
Create Date: 2026-08-06 16:06:53.050121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '279b177d4e6e'
down_revision: Union[str, None] = 'f260b6863262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_summaries', sa.Column('case_details', sa.JSON(), nullable=True))
    op.add_column('ai_summaries', sa.Column('background', sa.String(), nullable=True))
    op.add_column('ai_summaries', sa.Column('plaintiff_claims', sa.JSON(), nullable=True))
    op.add_column('ai_summaries', sa.Column('defendant_position', sa.JSON(), nullable=True))
    op.add_column('ai_summaries', sa.Column('reliefs_sought', sa.JSON(), nullable=True))
    op.add_column('ai_summaries', sa.Column('supporting_documents', sa.JSON(), nullable=True))
    op.add_column('ai_summaries', sa.Column('risk_assessment', sa.JSON(), nullable=True))
    op.add_column('ai_summaries', sa.Column('overall_summary', sa.String(), nullable=True))
    op.drop_column('ai_summaries', 'suggested_actions')
    op.drop_column('ai_summaries', 'risk_level')
    op.drop_column('ai_summaries', 'suggested_sections')
    op.drop_column('ai_summaries', 'case_summary')
    op.drop_column('ai_summaries', 'precedents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_summaries', sa.Column('precedents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_summaries', sa.Column('case_summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ai_summaries', sa.Column('suggested_sections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_summaries', sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ai_summaries', sa.Column('suggested_actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('ai_summaries', 'overall_summary')
    op.drop_column('ai_summaries', 'risk_assessment')
    op.drop_column('ai_summaries', 'supporting_documents')
    op.drop_column('ai_summaries', 'reliefs_sought')
    op.drop_column('ai_summaries', 'defendant_position')
    op.drop_column('ai_summaries', 'plaintiff_claims')
    op.drop_column('ai_summaries', 'background')
    op.drop_column('ai_summaries', 'case_details')
    # ### end Alembic commands ###
