"""Add AI Legal Models

Revision ID: 49d403047110
Revises: c57b6f890d25
Create Date: 2026-08-26 16:47:38.854981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49d403047110'
down_revision: Union[str, None] = 'c57b6f890d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create ENUMs manually for PostgreSQL
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'document_processing_status_enum') THEN CREATE TYPE document_processing_status_enum AS ENUM ('UPLOADED', 'PROCESSING', 'OCR_REQUIRED', 'TEXT_EXTRACTED', 'EMBEDDING_CREATED', 'READY', 'SUMMARY_GENERATING', 'SUMMARY_READY', 'FAILED'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'citation_verification_status_enum') THEN CREATE TYPE citation_verification_status_enum AS ENUM ('AI_SUGGESTED', 'ADVOCATE_VERIFIED', 'REJECTED'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'opinion_status_enum') THEN CREATE TYPE opinion_status_enum AS ENUM ('NOT_GENERATED', 'GENERATING', 'DRAFT', 'UNDER_REVIEW', 'REVISED', 'APPROVED', 'PDF_GENERATED'); END IF; END $$;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_analyses',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('executive_summary', sa.String(), nullable=True),
    sa.Column('material_facts', sa.JSON(), nullable=True),
    sa.Column('chronology', sa.JSON(), nullable=True),
    sa.Column('legal_issues', sa.JSON(), nullable=True),
    sa.Column('applicable_laws', sa.JSON(), nullable=True),
    sa.Column('evidence_assessment', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('missing_information', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('suggested_precedents', sa.JSON(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_GENERATED', 'GENERATING', 'READY', 'FAILED', name='case_analysis_status_enum'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['case_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_summaries',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('key_facts', sa.JSON(), nullable=True),
    sa.Column('important_dates', sa.JSON(), nullable=True),
    sa.Column('legal_references', sa.JSON(), nullable=True),
    sa.Column('potential_issues', sa.JSON(), nullable=True),
    sa.Column('evidence_found', sa.JSON(), nullable=True),
    sa.Column('missing_information', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['case_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('legal_opinion_versions',
    sa.Column('opinion_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opinion_id'], ['legal_opinions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('citations_category_id_fkey', 'citations', type_='foreignkey')
    op.drop_table('citation_categories')
    op.drop_table('opinion_revisions')
    op.drop_table('opinion_comments')
    op.add_column('case_documents', sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'OCR_REQUIRED', 'TEXT_EXTRACTED', 'EMBEDDING_CREATED', 'READY', 'SUMMARY_GENERATING', 'SUMMARY_READY', 'FAILED', name='document_processing_status_enum'), server_default='UPLOADED', nullable=False))
    op.add_column('case_documents', sa.Column('include_in_analysis', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('citations', sa.Column('case_name', sa.String(), server_default='Unknown Case', nullable=False))
    op.add_column('citations', sa.Column('citation', sa.String(), server_default=sa.text('md5(random()::text)'), nullable=False))
    op.add_column('citations', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('citations', sa.Column('legal_area', sa.String(), nullable=True))
    op.add_column('citations', sa.Column('principle', sa.Text(), nullable=True))
    op.add_column('citations', sa.Column('full_text', sa.Text(), nullable=True))
    op.add_column('citations', sa.Column('source', sa.String(), nullable=True))
    op.add_column('citations', sa.Column('verified', sa.Enum('AI_SUGGESTED', 'ADVOCATE_VERIFIED', 'REJECTED', name='citation_verification_status_enum'), server_default='AI_SUGGESTED', nullable=False))
    op.add_column('citations', sa.Column('embedding', sa.JSON(), nullable=True))
    op.add_column('citations', sa.Column('created_by', sa.UUID(), nullable=True))
    op.alter_column('citations', 'court',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('citations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('citations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_citations_reference_number', table_name='citations')
    op.create_index(op.f('ix_citations_case_name'), 'citations', ['case_name'], unique=False)
    op.create_index(op.f('ix_citations_citation'), 'citations', ['citation'], unique=True)
    op.create_foreign_key(None, 'citations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('citations', 'category_id')
    op.drop_column('citations', 'title')
    op.drop_column('citations', 'is_active')
    op.drop_column('citations', 'reference_number')
    op.drop_column('citations', 'citation_type')
    op.drop_column('citations', 'description')
    op.drop_column('citations', 'summary')
    op.drop_column('citations', 'keywords')
    op.drop_column('citations', 'jurisdiction')
    op.drop_column('citations', 'url')
    op.add_column('legal_opinions', sa.Column('case_analysis_id', sa.UUID(), nullable=True))
    op.add_column('legal_opinions', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('legal_opinions', sa.Column('documents_reviewed', sa.JSON(), nullable=True))
    op.add_column('legal_opinions', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('legal_opinions', sa.Column('brief_facts', sa.Text(), nullable=True))
    op.add_column('legal_opinions', sa.Column('applicable_law', sa.JSON(), nullable=True))
    op.add_column('legal_opinions', sa.Column('evidence_assessment', sa.Text(), nullable=True))
    op.add_column('legal_opinions', sa.Column('precedents', sa.JSON(), nullable=True))
    op.add_column('legal_opinions', sa.Column('strengths', sa.JSON(), nullable=True))
    op.add_column('legal_opinions', sa.Column('weaknesses', sa.JSON(), nullable=True))
    op.add_column('legal_opinions', sa.Column('risks', sa.JSON(), nullable=True))
    op.add_column('legal_opinions', sa.Column('conclusion', sa.Text(), nullable=True))
    op.add_column('legal_opinions', sa.Column('disclaimer', sa.Text(), nullable=True))
    op.add_column('legal_opinions', sa.Column('advocate_opinion', sa.Text(), nullable=True))
    op.add_column('legal_opinions', sa.Column('advocate_recommendations', sa.JSON(), nullable=True))
    op.add_column('legal_opinions', sa.Column('advocate_risk_assessment', sa.Text(), nullable=True))
    op.add_column('legal_opinions', sa.Column('advocate_notes', sa.Text(), nullable=True))
    op.add_column('legal_opinions', sa.Column('ai_model', sa.String(), nullable=True))
    op.add_column('legal_opinions', sa.Column('prompt_version', sa.String(), nullable=True))
    op.add_column('legal_opinions', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('legal_opinions', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('legal_opinions', sa.Column('signed_by', sa.UUID(), nullable=True))
    op.add_column('legal_opinions', sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('legal_opinions', sa.Column('signature_file', sa.String(), nullable=True))
    op.alter_column('legal_opinions', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'UNDER_REVIEW', 'FINALIZED', 'REJECTED', name='opinionstatus'),
               type_=sa.Enum('NOT_GENERATED', 'GENERATING', 'DRAFT', 'UNDER_REVIEW', 'REVISED', 'APPROVED', 'PDF_GENERATED', name='opinion_status_enum'),
               postgresql_using="CASE WHEN status::text = 'FINALIZED' THEN 'APPROVED'::opinion_status_enum WHEN status::text = 'REJECTED' THEN 'REVISED'::opinion_status_enum ELSE status::text::opinion_status_enum END",
               existing_nullable=False)
    op.alter_column('legal_opinions', 'issues',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using="to_json(issues)",
               existing_nullable=True)
    op.alter_column('legal_opinions', 'recommendations',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               postgresql_using="to_json(recommendations)",
               existing_nullable=True)
    op.drop_constraint('legal_opinions_advocate_id_fkey', 'legal_opinions', type_='foreignkey')
    op.create_foreign_key(None, 'legal_opinions', 'case_analyses', ['case_analysis_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'legal_opinions', 'users', ['signed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'legal_opinions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('legal_opinions', 'risk_level')
    op.drop_column('legal_opinions', 'finalized_at')
    op.drop_column('legal_opinions', 'facts')
    op.drop_column('legal_opinions', 'is_final')
    op.drop_column('legal_opinions', 'applicable_laws')
    op.drop_column('legal_opinions', 'summary')
    op.drop_column('legal_opinions', 'advocate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_opinions', sa.Column('advocate_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('legal_opinions', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('legal_opinions', sa.Column('applicable_laws', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('legal_opinions', sa.Column('is_final', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('legal_opinions', sa.Column('facts', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('legal_opinions', sa.Column('finalized_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('legal_opinions', sa.Column('risk_level', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'legal_opinions', type_='foreignkey')
    op.drop_constraint(None, 'legal_opinions', type_='foreignkey')
    op.drop_constraint(None, 'legal_opinions', type_='foreignkey')
    op.create_foreign_key('legal_opinions_advocate_id_fkey', 'legal_opinions', 'users', ['advocate_id'], ['id'], ondelete='SET NULL')
    op.alter_column('legal_opinions', 'recommendations',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('legal_opinions', 'issues',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('legal_opinions', 'status',
               existing_type=sa.Enum('NOT_GENERATED', 'GENERATING', 'DRAFT', 'UNDER_REVIEW', 'REVISED', 'APPROVED', 'PDF_GENERATED', name='opinion_status_enum'),
               type_=postgresql.ENUM('DRAFT', 'UNDER_REVIEW', 'FINALIZED', 'REJECTED', name='opinionstatus'),
               existing_nullable=False)
    op.drop_column('legal_opinions', 'signature_file')
    op.drop_column('legal_opinions', 'signed_at')
    op.drop_column('legal_opinions', 'signed_by')
    op.drop_column('legal_opinions', 'approved_at')
    op.drop_column('legal_opinions', 'created_by')
    op.drop_column('legal_opinions', 'prompt_version')
    op.drop_column('legal_opinions', 'ai_model')
    op.drop_column('legal_opinions', 'advocate_notes')
    op.drop_column('legal_opinions', 'advocate_risk_assessment')
    op.drop_column('legal_opinions', 'advocate_recommendations')
    op.drop_column('legal_opinions', 'advocate_opinion')
    op.drop_column('legal_opinions', 'disclaimer')
    op.drop_column('legal_opinions', 'conclusion')
    op.drop_column('legal_opinions', 'risks')
    op.drop_column('legal_opinions', 'weaknesses')
    op.drop_column('legal_opinions', 'strengths')
    op.drop_column('legal_opinions', 'precedents')
    op.drop_column('legal_opinions', 'evidence_assessment')
    op.drop_column('legal_opinions', 'applicable_law')
    op.drop_column('legal_opinions', 'brief_facts')
    op.drop_column('legal_opinions', 'instructions')
    op.drop_column('legal_opinions', 'documents_reviewed')
    op.drop_column('legal_opinions', 'version')
    op.drop_column('legal_opinions', 'case_analysis_id')
    op.add_column('citations', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('citations', sa.Column('jurisdiction', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('citations', sa.Column('keywords', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('citations', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('citations', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('citations', sa.Column('citation_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('citations', sa.Column('reference_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('citations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('citations', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('citations', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'citations', type_='foreignkey')
    op.create_foreign_key('citations_category_id_fkey', 'citations', 'citation_categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_citations_citation'), table_name='citations')
    op.drop_index(op.f('ix_citations_case_name'), table_name='citations')
    op.create_index('ix_citations_reference_number', 'citations', ['reference_number'], unique=False)
    op.alter_column('citations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('citations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('citations', 'court',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('citations', 'created_by')
    op.drop_column('citations', 'embedding')
    op.drop_column('citations', 'verified')
    op.drop_column('citations', 'source')
    op.drop_column('citations', 'full_text')
    op.drop_column('citations', 'principle')
    op.drop_column('citations', 'legal_area')
    op.drop_column('citations', 'year')
    op.drop_column('citations', 'citation')
    op.drop_column('citations', 'case_name')
    op.drop_column('case_documents', 'include_in_analysis')
    op.drop_column('case_documents', 'status')
    op.create_table('opinion_comments',
    sa.Column('opinion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='opinion_comments_author_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opinion_id'], ['legal_opinions.id'], name='opinion_comments_opinion_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='opinion_comments_pkey')
    )
    op.create_table('opinion_revisions',
    sa.Column('opinion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('revision_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('changes_summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='opinion_revisions_changed_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opinion_id'], ['legal_opinions.id'], name='opinion_revisions_opinion_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='opinion_revisions_pkey')
    )
    op.create_table('citation_categories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='citation_categories_pkey'),
    sa.UniqueConstraint('name', name='citation_categories_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('legal_opinion_versions')
    op.drop_table('document_summaries')
    op.drop_table('document_chunks')
    op.drop_table('case_analyses')
    # ### end Alembic commands ###
