"""Add meta_keywords to pages

Revision ID: 57968c72c6c7
Revises: dba70318a905
Create Date: 2026-08-20 14:09:55.194153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57968c72c6c7'
down_revision: Union[str, None] = 'dba70318a905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('meta_keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'meta_keywords')
    # ### end Alembic commands ###
