"""Add linkedin_url to advocate profiles

Revision ID: 6b7d86f0cd69
Revises: ddec8157cb0a
Create Date: 2026-08-17 19:04:43.536834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7d86f0cd69'
down_revision: Union[str, None] = 'ddec8157cb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advocate_profiles', sa.Column('linkedin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advocate_profiles', 'linkedin_url')
    # ### end Alembic commands ###
