"""Add default_hero_image_url

Revision ID: 71c9973fa8d3
Revises: f81eedb14fb4
Create Date: 2026-08-20 12:23:26.881356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c9973fa8d3'
down_revision: Union[str, None] = 'f81eedb14fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('default_hero_image_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'default_hero_image_url')
    # ### end Alembic commands ###
