"""Add featured_image_url to pages

Revision ID: 7f7a556ea1de
Revises: 423988827eb7
Create Date: 2026-08-19 16:40:39.317080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7a556ea1de'
down_revision: Union[str, None] = '423988827eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('featured_image_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'featured_image_url')
    # ### end Alembic commands ###
