"""Add PublicCase models

Revision ID: 9452f5ff8536
Revises: 48e93622dbf1
Create Date: 2026-08-18 11:43:03.626499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9452f5ff8536'
down_revision: Union[str, None] = '48e93622dbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_case_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_case_categories_name'), 'public_case_categories', ['name'], unique=True)
    op.create_index(op.f('ix_public_case_categories_slug'), 'public_case_categories', ['slug'], unique=True)
    op.create_table('public_case_tags_table',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_case_tags_table_name'), 'public_case_tags_table', ['name'], unique=True)
    op.create_index(op.f('ix_public_case_tags_table_slug'), 'public_case_tags_table', ['slug'], unique=True)
    op.create_table('public_cases',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['public_case_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_cases_slug'), 'public_cases', ['slug'], unique=True)
    op.create_table('public_case_tags',
    sa.Column('public_case_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['public_case_id'], ['public_cases.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['public_case_tags_table.id'], ),
    sa.PrimaryKeyConstraint('public_case_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_case_tags')
    op.drop_index(op.f('ix_public_cases_slug'), table_name='public_cases')
    op.drop_table('public_cases')
    op.drop_index(op.f('ix_public_case_tags_table_slug'), table_name='public_case_tags_table')
    op.drop_index(op.f('ix_public_case_tags_table_name'), table_name='public_case_tags_table')
    op.drop_table('public_case_tags_table')
    op.drop_index(op.f('ix_public_case_categories_slug'), table_name='public_case_categories')
    op.drop_index(op.f('ix_public_case_categories_name'), table_name='public_case_categories')
    op.drop_table('public_case_categories')
    # ### end Alembic commands ###
