"""Add legal matter fields to case

Revision ID: 983f09845dc1
Revises: 9fac9b2c89e6
Create Date: 2026-08-13 15:11:55.963760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983f09845dc1'
down_revision: Union[str, None] = '9fac9b2c89e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_type', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('incident_date', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('location', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('previous_legal_action', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('previous_case_info', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('opposing_party_name', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('opposing_party_type', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('additional_information', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'additional_information')
    op.drop_column('cases', 'opposing_party_type')
    op.drop_column('cases', 'opposing_party_name')
    op.drop_column('cases', 'previous_case_info')
    op.drop_column('cases', 'previous_legal_action')
    op.drop_column('cases', 'location')
    op.drop_column('cases', 'incident_date')
    op.drop_column('cases', 'case_type')
    # ### end Alembic commands ###
