"""Update notification models for enterprise notifications

Revision ID: 9fac9b2c89e6
Revises: 1733bd6f5384
Create Date: 2026-08-11 14:57:15.460744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fac9b2c89e6'
down_revision: Union[str, None] = '1733bd6f5384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.String(length=255), nullable=False),
    sa.Column('auth_key', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.add_column('notification_preferences', sa.Column('case_updates_enabled', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('document_updates_enabled', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('ai_updates_enabled', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('report_updates_enabled', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('payment_updates_enabled', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('account_updates_enabled', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('marketing_updates_enabled', sa.Boolean(), nullable=True))
    op.add_column('notification_preferences', sa.Column('system_updates_enabled', sa.Boolean(), nullable=True))
    from sqlalchemy.dialects.postgresql import ENUM
    notificationcategory = ENUM('AUTHENTICATION', 'ACCOUNT', 'ADVOCATE', 'CASE', 'DOCUMENT', 'AI', 'LEGAL_OPINION', 'REPORT', 'PAYMENT', 'NOTIFICATION', 'SUPPORT', 'SECURITY', 'SYSTEM', name='notificationcategory', create_type=False)
    notificationcategory.create(op.get_bind(), checkfirst=True)
    op.add_column('notifications', sa.Column('category', notificationcategory, nullable=True))
    op.add_column('notifications', sa.Column('entity_type', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('entity_id', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('action_url', sa.String(length=500), nullable=True))
    op.add_column('notifications', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'meta_data')
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'entity_type')
    op.drop_column('notifications', 'category')
    op.drop_column('notification_preferences', 'system_updates_enabled')
    op.drop_column('notification_preferences', 'marketing_updates_enabled')
    op.drop_column('notification_preferences', 'account_updates_enabled')
    op.drop_column('notification_preferences', 'payment_updates_enabled')
    op.drop_column('notification_preferences', 'report_updates_enabled')
    op.drop_column('notification_preferences', 'ai_updates_enabled')
    op.drop_column('notification_preferences', 'document_updates_enabled')
    op.drop_column('notification_preferences', 'case_updates_enabled')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
