"""add header_right_links to site_settings

Revision ID: aab908f3fd45
Revises: d2e82c00ddee
Create Date: 2026-08-19 18:31:46.069195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab908f3fd45'
down_revision: Union[str, None] = 'd2e82c00ddee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('header_right_links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'header_right_links')
    # ### end Alembic commands ###
