"""Add advocate registration models

Revision ID: ab967b5d8aa8
Revises: 4489d198e55f
Create Date: 2026-08-07 15:08:30.845884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab967b5d8aa8'
down_revision: Union[str, None] = '4489d198e55f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advocate_documents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advocate_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bar_council_number', sa.String(), nullable=False),
    sa.Column('bar_council_name', sa.String(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('practice_type', sa.String(), nullable=False),
    sa.Column('primary_practice_areas', sa.JSON(), nullable=False),
    sa.Column('secondary_practice_areas', sa.JSON(), nullable=True),
    sa.Column('languages_spoken', sa.JSON(), nullable=True),
    sa.Column('professional_summary', sa.String(), nullable=True),
    sa.Column('law_firm_name', sa.String(), nullable=True),
    sa.Column('office_address', sa.String(), nullable=True),
    sa.Column('office_phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_table('advocate_profiles')
    op.drop_table('advocate_documents')
    # ### end Alembic commands ###
