"""Add case_fee to cases

Revision ID: b9bf70d61cb5
Revises: 0f0556a444b3
Create Date: 2026-08-13 17:57:30.557388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9bf70d61cb5'
down_revision: Union[str, None] = '0f0556a444b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'case_fee')
    # ### end Alembic commands ###
