"""Add subtitle to section_contents

Revision ID: c57b6f890d25
Revises: 57968c72c6c7
Create Date: 2026-08-20 14:46:05.073409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57b6f890d25'
down_revision: Union[str, None] = '57968c72c6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_contents', sa.Column('subtitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section_contents', 'subtitle')
    # ### end Alembic commands ###
