"""Add statistics fields to site_settings

Revision ID: ca436a95c861
Revises: 5ee067909dd0
Create Date: 2026-08-19 20:05:42.720992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca436a95c861'
down_revision: Union[str, None] = '5ee067909dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('statistics_image_url', sa.String(length=512), nullable=True))
    op.add_column('site_settings', sa.Column('statistics_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'statistics_items')
    op.drop_column('site_settings', 'statistics_image_url')
    # ### end Alembic commands ###
