"""add header_links to site_settings

Revision ID: d2e82c00ddee
Revises: 8bbea2c3406b
Create Date: 2026-08-19 18:19:04.450205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e82c00ddee'
down_revision: Union[str, None] = '8bbea2c3406b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('header_links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'header_links')
    # ### end Alembic commands ###
