"""Add risk_level to LegalOpinion

Revision ID: d74975a6801b
Revises: 49d403047110
Create Date: 2026-08-27 15:36:20.541396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74975a6801b'
down_revision: Union[str, None] = '49d403047110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_opinions', sa.Column('risk_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_opinions', 'risk_level')
    # ### end Alembic commands ###
